#!/bin/sh

########################################################################
##
##  proxy-firewall-restrict
##  Configure Qubes firewall for use with a tunnel such as OpenVPN.
##
##  Note: For customization, add rules to a filename in firewall.d
##  other than '90_tunnel-restrict'.


groupadd -rf qvpn && sync

# Set firewall restriction policy

# Stop all leaks between downstream (vif+) and upstream (Internet eth0):
# NOTE: 1.b and its derivatives are apparently terminal actions (i.e. this
#       order may error by construction)
nft 'insert rule ip filter FORWARD drop' # 1.b
nft 'insert rule ip filter FORWARD oifname "eth0" counter drop'
nft 'insert rule ip filter FORWARD iifname "eth0" counter drop'

nft 'insert rule ip6 filter FORWARD drop' # 2.b
nft 'insert rule ip6 filter FORWARD oifname "eth0" counter drop'
nft 'insert rule ip6 filter FORWARD iifname "eth0" counter drop'

# Block INPUT from tunnel(s):
nft 'insert rule ip filter INPUT drop' # 3.b
nft 'insert rule ip6 filter INPUT drop' # 4.b

# Allow established v6 traffic (v4 rule already present):
#nft 'add rule ip filter INPUT ct state established counter accept'
nft 'add rule ip6 filter INPUT ct state established counter accept'

# Disable icmp packets
if [ -e /var/run/qubes-service/vpn-handler-no-icmp ]; then
  # 2 TODO
  iptables -D INPUT -p icmp -j ACCEPT  || true
  ip6tables -D INPUT -p icmp -j ACCEPT  || true
  nft 'insert rule ip filter OUTPUT oifname "eth0" ip protocol icmp counter drop'
  nft 'insert rule ip6 filter OUTPUT oifname "eth0" meta l4proto icmp counter drop'
else
  nft 'insert rule ip filter OUTPUT ip protocol icmp skgid 995 counter accept' # 7.b
  nft 'insert rule ip6 filter OUTPUT meta l4proto icmp skgid 995 counter accept' # 8.b
fi

###-------------------------------------------------------------------###
# This section executed only if vpn-handler-egress service _not_ enabled:
if [ -e /var/run/qubes-service/vpn-handler-egress ]; then
    exit 0
fi

# Extra restriction prevents accidental communications from within VPN VM to net;
# The gid-owner rule requires net programs be run with group ID 'qvpn'
# to allow outbound traffic.
nft 'insert rule ip filter OUTPUT drop' # 9.b
nft 'insert rule ip filter OUTPUT oifname "lo" counter accept'
nft 'insert rule ip filter OUTPUT oifname "eth0" skgid 995 counter accept' # 10.b

nft 'insert rule ip6 filter OUTPUT drop' # 11.b
nft 'insert rule ip6 filter OUTPUT oifname "lo" counter accept'
nft 'insert rule ip6 filter OUTPUT oifname "eth0" skgid 995 counter accept' # 12.b
