#!/bin/sh
export PATH="$PATH:/usr/sbin:/sbin:/bin"
[ `id -u` -eq 0 ] || exit 1

qvpnpath=/rw/config/vpn
upfile=userpassword.txt
tmppath=/tmp/$upfile

do_userpass () {
    bash /usr/lib/qubes/qubes-vpn-setup --userpass-bash
}

# Need bash for password prompt
do_userpass_bash () {
    echo
    echo "Enter VPN/tunnel login credentials."
    echo "Leave blank if not required..."
    echo
    read -p  "Username: " username
    read -s -p "Password: " upassword
    echo
    echo
    if [[ -z $username && -z $upassword ]]; then
      touch $qvpnpath/no-$upfile
      rm -f $qvpnpath/$upfile
      echo "Password login deactivated."
    else
      rm -f $qvpnpath/no-$upfile
      echo "$username" >$tmppath.tmp
      echo "$upassword" >>$tmppath.tmp
      chmod 600 $tmppath.tmp
      mv $tmppath.tmp $tmppath
      cp -a $tmppath $qvpnpath/$upfile
      echo -e "\nLogin info saved to $qvpnpath/$upfile"
    fi
    sleep 1s
    echo
}

# needs source dir passed as first arg
firewall_link () {
    # firewall for Qubes 4
    mkdir -p /rw/config/qubes-firewall.d
    ln -s -f $1/proxy-firewall-restrict \
    /rw/config/qubes-firewall.d/90_tunnel-restrict
}


case "$1" in
--check-firewall)
    for i in 1 2 3; do
        if iptables -C FORWARD -o eth0 -j DROP \
        && iptables -C FORWARD -i eth0 -j DROP ; then
            exit 0
        elif [ $i = 3 ]; then
            echo "Error: Firewall rule(s) not enabled!"
            exit 1
        fi
        sleep 2s
    done
;;

--pre-start)
    if [ ! -f $qvpnpath/$upfile ] && [ ! -f $qvpnpath/no-$upfile ]; then
        if [ ! -f /tmp/qvpn-askpass ]; then
            systemd-run --unit=qvpn-askpass -E DISPLAY=:0 sh -c \
            'sleep 2s; /usr/bin/xterm \
            -T "VPN Login" -e /usr/lib/qubes/qubes-vpn-setup --xterm'
        fi
    elif [ ! -f $tmppath ] && [ ! -f $qvpnpath/no-$upfile ]; then
        cp -aL $qvpnpath/$upfile $tmppath.tmp
        mv $tmppath.tmp $tmppath

    fi
    if [ -n "$filter_opts" ]; then
        # workaround for option parser bugs and overrides:
        # process config to remove options.
        grep -Ev '^[[:space:]]*('"$filter_opts"')[[:space:]]*' \
          $qvpnpath/vpn-client.conf  >/tmp/vpn-client.conf
    else
        cp -aL $qvpnpath/vpn-client.conf /tmp
    fi
    sync
    su - -c 'notify-send "$(hostname): Ready to start link."' user
;;

--start-exec)
    if [ -f $qvpnpath/no-$upfile ]; then
        userpassword_opt=""
    fi
    echo EXEC  $client_cmd $client_opt1 $client_opt2 $client_opt3 $client_opt4 \
      $client_opt5 $userpassword_opt
    eval $client_cmd $client_opt1 $client_opt2 $client_opt3 $client_opt4 \
      $client_opt5 $userpassword_opt
;;

--post-start)
    echo "START-ing network forwarding!"
    echo '1' > /proc/sys/net/ipv4/ip_forward
# '0' appears to be default setting for ipv6
#    echo '1' > /proc/sys/net/ipv6/conf/all/forwarding
;;

--post-stop)
    echo "STOP-ing network forwarding!"
    echo '0' > /proc/sys/net/ipv4/ip_forward
    echo '0' > /proc/sys/net/ipv6/conf/all/forwarding
;;

--install)

    if [ ! -d vpn ]; then exit 1; fi
    chown -R root:root *
    chmod +x rc.local qubes-vpn-ns qubes-vpn-setup proxy-firewall-restrict

    if [ -e /var/run/qubes/this-is-templatevm ]; then
        echo "Install into templateVM..."
        groupadd -rf qvpn
        cp -a qubes-vpn-handler.service* /lib/systemd/system
        sync; sleep 2s; systemctl daemon-reload
        systemctl enable qubes-vpn-handler.service
        cp -a qubes-vpn-ns qubes-vpn-setup proxy-firewall-restrict \
    -t /usr/lib/qubes
        echo "Almost done..."
        echo "Next, shutdown this template then start proxyVM and run:"
        echo "sudo /usr/lib/qubes/qubes-vpn-setup --config"

    elif [ -e /var/run/qubes/this-is-proxyvm ]; then
        echo -n "Isolated install for proxyVM..."
        cp -a vpn rc.local qubes-vpn-handler.service* qubes-vpn-setup \
    qubes-vpn-ns proxy-firewall-restrict -t /rw/config
        firewall_link /rw/config
        ln -s -f /rw/config/qubes-vpn-setup /usr/lib/qubes/qubes-vpn-setup
        ln -s -f /rw/config/qubes-vpn-ns /usr/lib/qubes/qubes-vpn-ns
        echo "copy complete."
        do_userpass
        echo "Done!"

    else
        echo "No appropriate VM type; Exiting."
        exit 1
    fi
;;

--config)
    . /usr/lib/qubes/init/functions
    if is_proxyvm ; then
        mkdir -p /rw/config/vpn
        firewall_link /usr/lib/qubes
        do_userpass
        echo "Done!"
    else
        echo "Error: Not a proxyVM. Check instructions."
    fi
;;

--config-nm)
    . /usr/lib/qubes/init/functions
    if is_proxyvm ; then
        firewall_link /usr/lib/qubes
        echo "Done!"
    else
        echo "Error: Not a proxyVM. Please check instructions."
        exit 1
    fi
;;

--xterm)
    touch /tmp/qvpn-askpass
    do_userpass
;;

--userpass-bash)
    do_userpass_bash
;;

--version)
    echo "1.4.1"
;;

esac

