#!/bin/bash

###########################################################################
##  qubes-vpn-ns
##
## Handles DHCP-source DNS addresses & link notification for Qubes VPN VMs.
## To use, set as 'up' and 'down' script with parameter in your VPN config.
##
## Use 'vpn_dns' environment var as override/alternative.
## In openvpn config, format is: setenv vpn_dns 'X.X.X.X  Y.Y.Y.Y [...]'
##
## Christopher Laprise, 2018-2020  -  https://github.com/tasket

set -e
export PATH="$PATH:/usr/sbin:/sbin:/bin"
nspath=/var/run/qubes/qubes-vpn-ns
rm -f $nspath
hostname=$(hostname)
nft "add table ip nat" || true
nft "add chain ip nat pr-qbs { type filter hook output priority 0 ; }" || true

do_notify() {
    if [ ! -e /etc/fedora-release-NONE ]; then
        echo \'"sleep 2; notify-send \"$hostname: $1\"" --icon=$2\' | xargs su - user -c &
    fi
}


case "$1" in
up|test-up)
    rm -f $nspath
    if [[ -z "$vpn_dns" ]] ; then
        # Parses DHCP option variables to set DNS address translation:
        for optionname in ${!foreign_option_*} ; do
            option="${!optionname}"
            unset fops; fops=($option)
            if [ ${fops[1]} == "DNS" ] ; then vpn_dns="${fops[2]} $vpn_dns" ; fi
        done
    fi

;;&
up)
    if [[ -n "$vpn_dns" ]] ; then
        # Set DNS address translation in firewall:
        echo "$vpn_dns " >$nspath
        echo "Using DNS servers $vpn_dns"
	nft flush chain ip nat pr-qbs
        . /var/run/qubes/qubes-ns
        q_addr=""
        for DNS in $vpn_dns; do
	    # maybe missing $q_addr? seems to be `""` at this call
	    nft 'insert rule ip nat pr-qbs iifname "vif*" tcp dport 53 counter dnat to ${DNS}'
	    nft 'insert rule ip nat pr-qbs iifname "vif*" udp dport 53 counter dnat to ${DNS}'
            q_addr="-d $NS1"
        done
        do_notify "LINK IS UP." "network-idle"
    else
        do_notify "LINK UP, NO DNS!" "dialog-error"
    fi

;;
test-up)

##  Use test-up parameter to test your basic VPN link before enabling firewall script.
##  Do NOT use beyond testing period.
    if [[ -z "$vpn_dns" ]]; then echo "NO DNS ADDRESS FOUND."; exit 0; fi
    [ -e /etc/resolv.vpnbak ] || cp -a /etc/resolv.conf /etc/resolv.vpnbak
    rm /etc/resolv.conf
    for DNS in $vpn_dns; do
        echo "nameserver $DNS" >>/etc/resolv.conf
    done
    /usr/lib/qubes/qubes-setup-dnat-to-ns
    do_notify "TEST LINK IS UP." "network-idle"

;;
down)
    nft flush chain ip nat pr-qbs
    do_notify "LINK IS DOWN !" "dialog-error"

;;
esac
