#!/bin/bash
uppath=/rw/config/vpn/userpassword.txt
tmppath="/tmp/"`basename $uppath`
if [ ! -f $uppath ]; then
    if [ ! "$1" = "xterm" ]; then
        if [ ! -f /tmp/vpn-askpass ]; then
            touch /tmp/vpn-askpass
#            sleep 2s
            systemd-run -E DISPLAY=:0 'sleep 3s; /usr/bin/xterm -T "VPN Login" \
-e /usr/lib/qubes/qubes-vpn-askpass xterm'
        fi
        exit 0
    else
        echo
        read -p  "VPN username: " username
        read -s -p "VPN password: " upassword
        echo
        echo
        echo "$username" >$tmppath
        echo "$upassword" >>$tmppath
        chmod 600 $tmppath
        read -N 1 -p "Save login info (Y/N)? " answer
        echo
        if [ "$answer" = "y" ] || [ "$answer" = "Y" ]; then
            cp -a $tmppath $uppath
            echo "Login info saved to $uppath"
            sleep 1s
        fi
    fi
else
    cp -a $uppath $tmppath
fi

