#!/bin/sh

########################################################################
##
##  qubes-firewall-user-script for use with a VPN client such as openvpn.
##
##

iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP
iptables -F OUTPUT

# Stop all leaks between downstream (AppVMs) and upstream (Internet):
iptables -I FORWARD -o eth0 -j DROP
iptables -I FORWARD -i eth0 -j DROP

# Add qvpn group and wait for change
if ! grep -q "^qvpn:" /etc/group ; then
    groupadd -rf qvpn
    sync
fi
sleep 2s

# Prevent accidental communications from within VPN VM;
# The gid-owner rule requires the VPN client be run with group ID 'qvpn'
# to allow outbound traffic from the client.
iptables -A OUTPUT -o lo -j ACCEPT
iptables -A OUTPUT -p all -o eth0 -m owner --gid-owner qvpn -m state --state NEW,ESTABLISHED -j ACCEPT

# Block INPUT from downstream and the tunnel:
iptables -I INPUT -i tun0 -j DROP
# Disable icmp packets
#if iptables -C INPUT -p icmp -j ACCEPT
#then iptables -D INPUT -p icmp -j ACCEPT
#fi

# Block all IPv6 traffic (generally unsupported in Qubes):
ip6tables -P OUTPUT DROP
ip6tables -F OUTPUT
ip6tables -P FORWARD DROP
ip6tables -F FORWARD
ip6tables -P INPUT DROP
ip6tables -F INPUT

# Fix nameserver IPs in FORWARD
/usr/lib/qubes/vpn-ns-handler fwupdate

